name: MLOps Sanity Check

on:
  pull_request:
    branches: [ main ]

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install CML
      run: npm install -g @dvcorg/cml

    - name: Install dependencies
      working-directory: week4
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      working-directory: week4
      run: python src/train.py

    - name: Evaluate model
      working-directory: week4
      run: python src/evaluate.py

    - name: Run unit tests
      working-directory: week4
      run: |
        pytest src/test_model.py | tee test_output.txt

    - name: Post CML report to PR
      working-directory: week4
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## Test Results" > report.md 
        echo '```' >> report.md
        cat test_output.txt >> report.md
        echo '```' >> report.md
        echo "##  Metrics" >> report.md 
        cat metrics.csv >> report.md
        npx cml comment create report.md

