name: Sanity Tests with Pytest and CML

on:
  pull_request:
    branches: [main]

jobs:
  sanity-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pytest and save report
      run: |
        pytest src/ > report.txt || true

    - name: Comment test report using CML
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install cml
        cml comment create report.txt

